name: DevOps CI (Local Runner)

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devops-projekti .
          echo "Docker image buildattu!"

      - name: Stop old container if exists
        run: |
          docker stop testi || echo "Ei vanhaa konttia"
          docker rm testi || echo "Ei poistettavaa"

      - name: Run Docker container locally
        run: |
          docker run -d -p 8080:80 --name testi devops-projekti
          echo "Uusi kontti käynnissä!"
