name: DevOps CI (Local Runner)

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devops-projekti .
          echo "Docker image buildattu!"

      - name: Stop and remove old container
        shell: pwsh
        run: |
          $container = docker ps -a -q -f "name=testi"
          if ($container) {
            Write-Host "Stopping old container..."
            docker stop $container | Out-Null
            Write-Host "Removing old container..."
            docker rm $container | Out-Null
          } else {
            Write-Host "No old container found"
          }

      - name: Run Docker container locally
        run: |
          docker run -d -p 8080:80 --name testi devops-projekti
          echo "Uusi kontti käynnissä!"
